# Урок 2. Метрики качества классификации ч.1

В уроке мы разбирали матрицу ошибок и некоторые метрики, основанные на терминах матрицы ошибок. Здесь же посмотрим, как эти метрики применять на практике и что  по ним можно выяснить.

### 1.1
Выкачайте тренировочный датасет Titanic - train.csv - с сайта [kaggle](https://www.kaggle.com/c/titanic/data). С помощью функции pd.read_csv() загрузите данные в датафрейм. Выведите первые 20 строк и проанализируйте данные: какие колонки присутствуют (более конкретная информация по ним есть на сайте kaggle), каким образом в них обозначены данные и какие типы данных используются (используйте pandas.dtypes).

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('train.csv')
df.head(20)

PassengerId  Survived  Pclass  \
0             1         0       3   
1             2         1       1   
2             3         1       3   
3             4         1       1   
4             5         0       3   
5             6         0       3   
6             7         0       1   
7             8         0       3   
8             9         1       3   
9            10         1       2   
10           11         1       3   
11           12         1       1   
12           13         0       3   
13           14         0       3   
14           15         0       3   
15           16         1       2   
16           17         0       3   
17           18         1       2   
18           19         0       3   
19           20         1       3   

                                                 Name     Sex   Age  SibSp  \
0                             Braund, Mr. Owen Harris    male  22.0      1   
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                              Heikkinen, Miss. Laina  female  26.0      0   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                            Allen, Mr. William Henry    male  35.0      0   
5                                    Moran, Mr. James    male   NaN      0   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
7                      Palsson, Master. Gosta Leonard    male   2.0      3   
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   
12                     Saundercock, Mr. William Henry    male  20.0      0   
13                        Andersson, Mr. Anders Johan    male  39.0      1   
14               Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                   Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                               Rice, Master. Eugene    male   2.0      4   
17                       Williams, Mr. Charles Eugene    male   NaN      0   
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                            Masselmani, Mrs. Fatima  female   NaN      0   

    Parch            Ticket     Fare Cabin Embarked  
0       0         A/5 21171   7.2500   NaN        S  
1       0          PC 17599  71.2833   C85        C  
2       0  STON/O2. 3101282   7.9250   NaN        S  
3       0            113803  53.1000  C123        S  
4       0            373450   8.0500   NaN        S  
5       0            330877   8.4583   NaN        Q  
6       0             17463  51.8625   E46        S  
7       1            349909  21.0750   NaN        S  
8       2            347742  11.1333   NaN        S  
9       0            237736  30.0708   NaN        C  
10      1           PP 9549  16.7000    G6        S  
11      0            113783  26.5500  C103        S  
12      0         A/5. 2151   8.0500   NaN        S  
13      5            347082  31.2750   NaN        S  
14      0            350406   7.8542   NaN        S  
15      0            248706  16.0000   NaN        S  
16      1            382652  29.1250   NaN        Q  
17      0            244373  13.0000   NaN        S  
18      0            345763  18.0000   NaN        S  
19      0              2649   7.2250   NaN        C

In [4]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

### 1.2
Проверьте, имеются ли пропущенные значения в колонках, и выведите сумму всех пропущенных значений в каждой из колонок.

In [5]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [6]:
null_df = df.isnull().sum()
# null_df = null_df.sum()
null_df

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

### 1.3
Замените все пропущенные значения колонки Age на медианы в зависимости от пола человека: т.е. если пол человека в строке с пропущенным значением "male", заменяете пропущенное значение возраста на медиану по всем известным возрастам мужчин, и наоборот. Выведите медианы возраста в зависимости от пола. Пропущенные значения колонок Cabin и Embarked замените на U (Unknown).

Примечание: для группировки по полу можно использовать метод df.groupby(), который имеет встроенные агрегатные функции (в т.ч. для вычисления медианы).  Для установки пропущенных значений в датасете воспользуйтесь функцией df.apply().

In [7]:
print('Cabin null values: %.2d'
      '\nEmbarked null values: %.2d' % (df['Cabin'].isnull().sum(), df['Embarked'].isnull().sum()))

Cabin null values: 687
Embarked null values: 02


In [8]:
df = pd.read_csv('train.csv')

male, female = df.groupby('Sex')['Age'].mean()

# df['Age'] = df.groupby('Sex')['Age'].apply(lambda x: x.fillna(x.mean()))
df['Age'] = df.groupby('Sex')['Age'].apply(lambda x: x.fillna(x.mean())).reset_index(drop=True)

df['Cabin'].fillna('U', inplace=True)
df['Embarked'].fillna('U', inplace=True)

print('male median: %.3f, female median: %.3f' % (male, female))
print('Cabin null values: %.2d'
      '\nEmbarked null values: %.2d' % (df['Cabin'].isnull().sum(), df['Embarked'].isnull().sum()))

male median: 27.916, female median: 30.727
Cabin null values: 00
Embarked null values: 00


### 1.4
Выведите возраст пассажиров с PassengerID = [6, 20]. Убедитесь, что заполнены все пропущенные значения (воспользуйтесь функцией df.isnull() ).

In [9]:
df.isnull().sum().sum()
pas_id = list(range(6, 21))

print(df[df['PassengerId'].isin(pas_id)]['Age'].astype(int))


5      4
6     58
7     14
8     55
9     31
10    27
11    15
12     8
13    38
14    27
15    27
16    27
17    18
18    14
19    40
Name: Age, dtype: int64


Так как не все классификаторы могут работать с категориальными признаками, в данном случае необходимо заменить их на числовые.

Также можно было бы выделить расширенные признаки, такие как статус пассажира (Mr., Mrs., Miss., Dr., Master. и т.д.), собственный индекс билета, индекс палубы и другие, но здесь ограничимся выбором более простых признаков.

### 1.5
В колонке Sex замените значения на 0, если пол "male", и на 1, если "female". В колонке Embarked замените параметры "U", "S", "C", "Q" на 0, 1, 2, 3 соответственно. Отбросьте колонки PassengerId, Name, Ticket, Cabin. Выведите первые 20 строк получившегося набора данных.

In [10]:
df_mod = df.copy()

df_mod['Sex'].replace({'male':0, 'female':1}, inplace=True)
df_mod['Embarked'].replace({'U':0, 'S':1, "C":2, 'Q':3}, inplace=True)

df_mod.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1, inplace=True)

df_mod.head(20)

Survived  Pclass  Sex        Age  SibSp  Parch     Fare  Embarked
0          0       3    0  38.000000      1      0   7.2500         1
1          1       1    1  26.000000      1      0  71.2833         2
2          1       3    1  35.000000      0      0   7.9250         1
3          1       1    1  27.000000      1      0  53.1000         1
4          0       3    0  14.000000      0      0   8.0500         1
5          0       3    0   4.000000      0      0   8.4583         3
6          0       1    0  58.000000      0      0  51.8625         1
7          0       3    0  14.000000      3      1  21.0750         1
8          1       3    1  55.000000      0      2  11.1333         1
9          1       2    1  31.000000      1      0  30.0708         2
10         1       3    1  27.915709      1      1  16.7000         1
11         1       1    1  15.000000      0      0  26.5500         1
12         0       3    0   8.000000      0      0   8.0500         1
13         0       3    0  38.000000      1      5  31.2750         1
14         0       3    1  27.915709      0      0   7.8542         1
15         1       2    1  27.915709      0      0  16.0000         1
16         0       3    0  27.915709      4      1  29.1250         3
17         1       2    0  18.000000      0      0  13.0000         1
18         0       3    1  14.000000      1      0  18.0000         1
19         1       3    1  40.000000      0      0   7.2250         2

### 1.6
Приступим к построению классификаторов. **Условимся, что, если функция или объект модели имеют параметр random_state, то устанавливаем его равным 17 в каждом из случаев.**

Разделите данные на тренировочный и тестовый датасеты, установив размер тестового как 0.25 (первая колонка Survived является целевой, поэтому необходимо сначала ее отделить от признаков).

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
features = df_mod.drop('Survived', axis=1).to_numpy()
features.shape

(891, 7)

In [102]:
features = df_mod.drop('Survived', axis=1).to_numpy()
target = df_mod['Survived']

x_train, x_test, y_train, y_test = train_test_split(features, target, test_size=.25, random_state=17)
x_train.shape

(668, 7)

### 1.7
Обучите на полученных выборках несколько классификаторов, которые импортированы ниже.

**Примечание: в методе ближайших соседей используйте количество соседей, равное 5.**

In [103]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

In [104]:
knn = KNeighborsClassifier(n_neighbors=5)
knn_model = knn.fit(x_train, y_train)

nb = GaussianNB()
nb_model = nb.fit(x_train, y_train)

dtc = DecisionTreeClassifier()
dtc_model = dtc.fit(x_train, y_train)

log_reg = LogisticRegression(max_iter=150)
log_reg_model = log_reg.fit(x_train, y_train)



Очевидно, в этом случае использовать метрику accuracy, которую мы применяли до этого, не совсем правильно: она не даст верную оценку классификатору, потому как выживших явно меньше, чем погибших.

Вспомним про такие метрики как точность и полнота. Здесь они подойдут хорошо, так как у нас имеются положительный и отрицательный классы, и определить корректно один из них может оказаться более важным .

### 1.8
В каждом из пунктов следующего теста выберите, что важнее максимизировать: точность (precision) или полноту (recall). Выпишите ответы.

1. Вероятность того, что при определенной поломке самолета он сможет долететь до пункта назначения (1 - долетел, 0 - не долетел).
2. Предсказание, представляет ли человек опасность, по анализу психического состояния (1 - представляет опасность, 0 - не представляет опасности).
3. Предсказание ухода клиента (1 - клиент ушел, 0 - остался).
4. Выявление рака на основе медицинских показателей (1 - болен раком, 0 - здоров).
5. Предсказание летальности при наблюдаемой мутации (1 - выживание, 0 - летальный исход).
6. Определение важности происшествия для экстренных служб (1 - важно, 0 - неважно).
7. Окупятся ли вложения в бизнес (1 - окупятся, 0 - не окупятся).

Ваш ответ:

1. <br>Precision
2. <br>Recall
3. <br>Recall
4. <br>Recall
5. <br>Precision
6. <br>Recall
7. <br>Precision

###Пояснение:
Для датасета Титаник важнее использовать метрику recall, т.к. при условном поиске выживших нам важнее количество ложно-отрицательных данных, те кого модель посчитала погибшими, но на самом деле, выжившие###

### 1.9
Определите, что важнее использовать в случае датасета Titanic: полноту или точность. Объясните, почему.

### 1.10
Для каждого классификатора выведите матрицу ошибок и самостоятельно рассчитайте метрику recall (расчеты должны присутствовать). Проверьте расчеты, воспользовавшись встроенной метрикой recall_score.

In [105]:
from sklearn.metrics import confusion_matrix, recall_score

In [113]:
# tn, fp, fn, tp = confusion_matrix([0, 1, 0, 1], [1, 1, 1, 0]).ravel()
# (tn, fp, fn, tp)

(0, 2, 1, 1)

In [115]:
dict_matrix = {'Knn matrix': knn_model,
               'Naive bayes matrix': nb_model,
               'Decision tree matrix': dtc_model,
               'Logistic regression matrix': log_reg_model}

for i, j in dict_matrix.items():
  tm = confusion_matrix(y_test, j.predict(x_test))
  rec_score = tm[1,1] / (tm[1,1] + tm[1,0])
  true_rec_score = recall_score(y_test, j.predict(x_test))

  print(f'{i}:\n {tm}\n')
  print('recall score for %.30s: %.5f' % (i, rec_score))
  print('true recall score: %.5f' % (true_rec_score), '\n')

Knn matrix:
 [[108  23]
 [ 55  37]]

recall score for Knn matrix: 0.40217
true recall score: 0.40217 

Naive bayes matrix:
 [[111  20]
 [ 29  63]]

recall score for Naive bayes matrix: 0.68478
true recall score: 0.68478 

Decision tree matrix:
 [[99 32]
 [26 66]]

recall score for Decision tree matrix: 0.71739
true recall score: 0.71739 

Logistic regression matrix:
 [[114  17]
 [ 30  62]]

recall score for Logistic regression matrix: 0.67391
true recall score: 0.67391 



### 1.11
Выберите ту модель, на которой метрика recall давала лучший ответ, и рассчитайте для нее precision, используя встроенную функцию.

In [117]:
from sklearn.metrics import precision_score

In [120]:
pr_score = precision_score(y_test, dtc_model.predict(x_test))

print(f'precision score: {pr_score}')




precision score: 0.673469387755102
